name: pjh_zhtox_swift 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10    
  - pip
  - pip:
      - torch
      - torchvision
      - transformers>=4.51
      - ms-swift
      - peft==0.15.2
      - trl==0.17
      - deepspeed==0.14.5
      - vllm==0.8
      - bitsandbytes>=0.45.5
      - accelerate==1.6.0
      - opencv-python
      - wandb
      - timm